# Site settings
author: Amanda Murphy
title: A Good Unicorn
header-img: img/home-bg.png
email: helloamandamurphy@gmail.com
copyright_name: Amanda Murphy
description: > # this means to ignore newlines until "baseurl:"
  Doing All The Things
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: babiescatscode
github_username:  helloamandamurphy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
